version: '3.8'

services:
  postgres:
    image: postgres:15.1
    container_name: postgresql-sortelancada
    restart: unless-stopped
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - '5436:5432'
    volumes:
      - pgdata_sortelancada:/var/lib/postgresql/data

volumes:
  pgdata_sortelancada:
